version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Map frontend container's port 3000 to host
    depends_on:
      - backend # Start backend first
    environment:
      REACT_APP_API_URL: "http://localhost:3000" # Connect to the backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000" # Map backend container's port 5000 to host
    environment:
      FASTAPI_ENV: development
